### ISSUE TITLE
Visible IBAN in Cashback section

### ISSUE THREAD

**Issue by NiccoloSegato** [pagopa/io-app#2559]
**Problem description**
In the cashback section, the IBAN label is shown in clear text. It would be safer and more compliant with industry standards to obscure all fields except the last few digits, thus making the system even more secure.

**To Reproduce**
1. Go to 'Portafoglio'
2. Click on 'Cashback' blue card
3. Scroll down to the bottom at 'IBAN per l'accredito'

**Expected behavior**
The label showing the user's IBAN should obscure most of the digits, making the account number not legible but still recognizable.

**Screenshots**
![photo_2020-12-11_01-30-49](https://user-images.githubusercontent.com/25075007/101842397-3b175100-3b48-11eb-80ff-43b9527a5c1c.jpg)

**App version**
1.14.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 14.2

**Additional context**
Keep going 😉

**Comment by mzzntn** [comment]
Ciao @NiccoloSegato, the IBAN code is not considered personal information therefore it doesn't require any special system to obscure it. 

The IBAN code is only useful to receive payments and can't be use in any other way :)

**Comment by bhack** [comment]
I think It Is better the have a show/hide toogle:
https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/3134436

**Comment by NiccoloSegato** [comment]
Acccording to @bhack message, a simple show/hide toggle is a great solution.
Even if the IBAN is not considered a private data, I think that give the possibility to hide the code is a fundamental feature improving the user security.

**Comment by thisisjp** [comment]
Thanks for your suggestion @NiccoloSegato!
We'll consider your suggestion when planning our future app releases.

As already mentioned before, IBAN is not a sensitive information that can be used to perform payments (same reason why we hide your card PAN instead). Nevertheless, we take security very seriously by design: when you switch between apps, for instance, we hide all the content and require you to enter your unlock code (or use your face/fingerprint).
